In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
movie_gross = pd.read_csv('/home/mungai/Downloads/dsc-phase-1-project-master/zippedData/bom.movie_gross.csv')
movie_gross

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [3]:
#check for missing values
movie_gross.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [23]:
#calculate percentage of missing data in the data
movie_gross.isna().sum()*100/len(movie_gross)

title              0.000000
studio             0.147623
domestic_gross     0.826690
foreign_gross     39.858282
year               0.000000
dtype: float64

In [24]:
#create a non null column of foreign_gross
non_null = movie_gross[movie_gross['foreign_gross'].notna()]
non_null

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3275,I Still See You,LGF,1400.0,1500000,2018
3286,The Catcher Was a Spy,IFC,725000.0,229000,2018
3309,Time Freak,Grindstone,10000.0,256000,2018
3342,Reign of Judges: Title of Liberty - Concept Short,Darin Southa,93200.0,5200,2018
3353,Antonio Lopez 1970: Sex Fashion & Disco,FM,43200.0,30000,2018

In [22]:
#change the foreign gross column data from object to integer
non_null = movie_gross['foreign_gross'].replace(',', '').astype(float).astype(int)
type(non_null['foreign_gross'])

ValueError: could not convert string to float: '1,131.6'

In [49]:
#find the mean, mode and median of foreign gross
mean = int(non_null['foreign_gross']).mean()
mode = int(non_null['foreign_gross']).mode()
median = int(non_null['foreign_gross']).median()

print({'mean':mean, 'mode':mode, 'median':median})

TypeError: cannot convert the series to <class 'int'>